FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:20-slim
WORKDIR /app
RUN npm install -g serve
COPY --from=0 /app/dist ./dist
CMD ["serve", "-s", "dist", "-l", "3000"]
